name: "Alexa Shopping List bridge"
description: "Alexa shopping list bridge to integrate shopping lists with HASS"
version: "0.0.5"
slug: "alexa_shopping_list_bridge"
image: "shadyabhi/alexa-shopping-list-bridge"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
environment:
  CONFIG: /data/options.json

options:
  app:
    data_dir: "/config"
    log_level: "info"
  amazon:
    domain: "www.amazon.com"
  hass:
    base_url: "http://192.168.1.208:8123"
    username: "shopping_list_alexa"
    password: ""
schema:
  app:
    data_dir: str
    log_level: list(debug|info|warn|error)
  amazon:
    domain: str
  hass:
    base_url: str
    username: str
    password: str
map:
  - type: addon_config
    read_only: false
    path: /config
